##################################
#                                #
#   这里是NetConsole的配置文件   #
#                                #
##################################

#这里填写语言文件的文件名
local: zh_cn

#初始化设置, 在启动和关闭时是否初始化
initialize:
    install: true
    cancel: true

